# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - copyloopvar
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-blank: false
    # Ignore fire-and-forget writes in proxy (performance critical)
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - io.Copy
      - (*os.File).Write
      - (*os.File).Sync
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G104  # Unhandled errors (handled via errcheck exclude)
      - G304  # File inclusion via variable (intentional in config)

issues:
  exclude-dirs:
    - tests
  
  exclude-rules:
    # Exclude test files from most linters
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - bodyclose
    
    # Allow unused parameters in interface implementations
    - linters:
        - unused
      text: "parameter .* seems to be unused"
    
    # Allow unchecked store operations (fire-and-forget cache)
    - linters:
        - errcheck
      text: "Error return value of .*(store|Store).*"
    
    # Allow unchecked json.Unmarshal in handlers (validated elsewhere)
    - linters:
        - errcheck  
      text: "Error return value of `json.Unmarshal`"

  max-issues-per-linter: 50
  max-same-issues: 5
