// Tool session management for hybrid tool discovery.
//
// DESIGN: Stores deferred tools (filtered out) and expanded tools (retrieved via search)
// per session. Used to enable the LLM to request tools that were filtered out.
//
// FLOW:
//  1. Tool discovery pipe filters tools, stores deferred tools in session
//  2. Gateway injects gateway_search_tools into the tools list
//  3. If LLM calls gateway_search_tools, gateway searches deferred tools
//  4. Matching tools are marked as "expanded" and included in subsequent requests
//
// Session ID is derived from the first user message hash (same as preemptive summarization).
package gateway

import (
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/compresr/context-gateway/internal/adapters"
)

// ToolCallMapping stores the bidirectional ID mapping for a single tool call
// that was dispatched through gateway_search_tool.
type ToolCallMapping struct {
	ProxyToolUseID  string         // The tool_use ID generated by the LLM (for gateway_search_tool)
	ClientToolName  string         // The real tool name the client sees (e.g., "Read")
	ClientToolUseID string         // The tool_use ID the client sees (generated by proxy)
	OriginalInput   map[string]any // The original tool_input (for inbound rewriting)
}

// ToolSession stores deferred and expanded tools for a single session.
type ToolSession struct {
	SessionID      string
	DeferredTools  []adapters.ExtractedContent // Tools filtered out by relevance scoring
	ExpandedTools  map[string]bool             // Tool names that were searched and found
	CreatedAt      time.Time
	LastAccessedAt time.Time

	// RewriteMap: clientToolUseID -> mapping
	// Used for bidirectional rewriting between client and LLM.
	RewriteMap map[string]*ToolCallMapping

	// Search loop-breaking state
	SearchCallCount     int      // How many search-mode calls in current phantom loop sequence
	DiscoveredToolNames []string // Tools the model has seen via search results
}

// ToolSessionStore manages tool sessions with automatic TTL cleanup.
type ToolSessionStore struct {
	sessions map[string]*ToolSession
	mu       sync.RWMutex
	ttl      time.Duration
}

// NewToolSessionStore creates a new tool session store.
func NewToolSessionStore(ttl time.Duration) *ToolSessionStore {
	if ttl == 0 {
		ttl = time.Hour // Default 1 hour TTL
	}
	store := &ToolSessionStore{
		sessions: make(map[string]*ToolSession),
		ttl:      ttl,
	}
	// Start background cleanup
	go store.cleanupLoop()
	return store
}

// Reset clears all tool sessions for a fresh start.
func (s *ToolSessionStore) Reset() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.sessions = make(map[string]*ToolSession)
}

// Get retrieves a session by ID (returns nil if not found).
func (s *ToolSessionStore) Get(sessionID string) *ToolSession {
	s.mu.RLock()
	defer s.mu.RUnlock()

	session, ok := s.sessions[sessionID]
	if !ok {
		return nil
	}
	return session
}

// StoreDeferred stores deferred tools for a session.
func (s *ToolSessionStore) StoreDeferred(sessionID string, deferred []adapters.ExtractedContent) {
	s.mu.Lock()
	defer s.mu.Unlock()

	session, ok := s.sessions[sessionID]
	if !ok {
		session = &ToolSession{
			SessionID:      sessionID,
			ExpandedTools:  make(map[string]bool),
			RewriteMap:     make(map[string]*ToolCallMapping),
			CreatedAt:      time.Now(),
			LastAccessedAt: time.Now(),
		}
		s.sessions[sessionID] = session
	}
	session.DeferredTools = deferred
	session.LastAccessedAt = time.Now()
}

// GetDeferred retrieves deferred tools for a session.
// Note: Does not update LastAccessedAt to avoid write under read lock.
// The session will be refreshed when StoreDeferred or MarkExpanded is called.
func (s *ToolSessionStore) GetDeferred(sessionID string) []adapters.ExtractedContent {
	s.mu.RLock()
	defer s.mu.RUnlock()

	session, ok := s.sessions[sessionID]
	if !ok {
		return nil
	}
	// Return a copy to avoid races
	result := make([]adapters.ExtractedContent, len(session.DeferredTools))
	copy(result, session.DeferredTools)
	return result
}

// MarkExpanded marks tools as expanded (found via search).
func (s *ToolSessionStore) MarkExpanded(sessionID string, toolNames []string) {
	s.mu.Lock()
	defer s.mu.Unlock()

	session, ok := s.sessions[sessionID]
	if !ok {
		session = &ToolSession{
			SessionID:      sessionID,
			ExpandedTools:  make(map[string]bool),
			RewriteMap:     make(map[string]*ToolCallMapping),
			CreatedAt:      time.Now(),
			LastAccessedAt: time.Now(),
		}
		s.sessions[sessionID] = session
	}
	for _, name := range toolNames {
		session.ExpandedTools[name] = true
	}
	session.LastAccessedAt = time.Now()
}

// GetExpanded retrieves expanded tool names for a session.
func (s *ToolSessionStore) GetExpanded(sessionID string) map[string]bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	session, ok := s.sessions[sessionID]
	if !ok {
		return nil
	}
	// Return a copy to avoid races
	result := make(map[string]bool, len(session.ExpandedTools))
	for k, v := range session.ExpandedTools {
		result[k] = v
	}
	return result
}

// cleanupLoop periodically removes expired sessions.
func (s *ToolSessionStore) cleanupLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()

	for range ticker.C {
		s.cleanup()
	}
}

// cleanup removes expired sessions.
func (s *ToolSessionStore) cleanup() {
	s.mu.Lock()
	defer s.mu.Unlock()

	cutoff := time.Now().Add(-s.ttl)
	for id, session := range s.sessions {
		if session.LastAccessedAt.Before(cutoff) {
			delete(s.sessions, id)
		}
	}
}

// =============================================================================
// REWRITE MAP (Universal Dispatcher)
// =============================================================================

// RecordCallRewrite stores a mapping for bidirectional rewriting.
// Called when the proxy rewrites a gateway_search_tool call to a real tool call.
func (s *ToolSessionStore) RecordCallRewrite(sessionID string, mapping *ToolCallMapping) {
	s.mu.Lock()
	defer s.mu.Unlock()
	session := s.getOrCreate(sessionID)
	session.RewriteMap[mapping.ClientToolUseID] = mapping
	session.LastAccessedAt = time.Now()
}

// GetRewriteMapping looks up a mapping by the client-facing tool_use_id.
func (s *ToolSessionStore) GetRewriteMapping(sessionID, clientToolUseID string) *ToolCallMapping {
	s.mu.RLock()
	defer s.mu.RUnlock()
	session, ok := s.sessions[sessionID]
	if !ok || session.RewriteMap == nil {
		return nil
	}
	return session.RewriteMap[clientToolUseID]
}

// GetAllRewriteMappings returns a copy of all mappings for a session.
// Used by inbound rewriting to transform the full message history.
func (s *ToolSessionStore) GetAllRewriteMappings(sessionID string) map[string]*ToolCallMapping {
	s.mu.RLock()
	defer s.mu.RUnlock()
	session, ok := s.sessions[sessionID]
	if !ok || session.RewriteMap == nil {
		return nil
	}
	result := make(map[string]*ToolCallMapping, len(session.RewriteMap))
	for k, v := range session.RewriteMap {
		result[k] = v
	}
	return result
}

// IncrementSearchCount increments the search call counter and returns the new count.
func (s *ToolSessionStore) IncrementSearchCount(sessionID string) int {
	s.mu.Lock()
	defer s.mu.Unlock()
	session := s.getOrCreate(sessionID)
	session.SearchCallCount++
	session.LastAccessedAt = time.Now()
	return session.SearchCallCount
}

// ResetSearchCount resets the search call counter (called on successful tool execution).
func (s *ToolSessionStore) ResetSearchCount(sessionID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if session, ok := s.sessions[sessionID]; ok {
		session.SearchCallCount = 0
		session.LastAccessedAt = time.Now()
	}
}

// AddDiscoveredToolNames appends tool names to the session's discovered list.
func (s *ToolSessionStore) AddDiscoveredToolNames(sessionID string, names []string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	session := s.getOrCreate(sessionID)
	session.DiscoveredToolNames = append(session.DiscoveredToolNames, names...)
	session.LastAccessedAt = time.Now()
}

// getOrCreate returns an existing session or creates a new one.
// Must be called under write lock.
func (s *ToolSessionStore) getOrCreate(sessionID string) *ToolSession {
	session, ok := s.sessions[sessionID]
	if !ok {
		session = &ToolSession{
			SessionID:      sessionID,
			ExpandedTools:  make(map[string]bool),
			RewriteMap:     make(map[string]*ToolCallMapping),
			CreatedAt:      time.Now(),
			LastAccessedAt: time.Now(),
		}
		s.sessions[sessionID] = session
	}
	// Ensure maps are initialized (session may have been created by StoreDeferred/MarkExpanded)
	if session.RewriteMap == nil {
		session.RewriteMap = make(map[string]*ToolCallMapping)
	}
	if session.ExpandedTools == nil {
		session.ExpandedTools = make(map[string]bool)
	}
	return session
}

// =============================================================================
// TOOL SEARCH
// =============================================================================

// SearchDeferredTools searches deferred tools by query.
// Returns top matches sorted by relevance score.
func SearchDeferredTools(deferred []adapters.ExtractedContent, query string, maxResults int) []adapters.ExtractedContent {
	if len(deferred) == 0 || query == "" {
		return nil
	}

	if maxResults <= 0 {
		maxResults = 5
	}

	queryLower := strings.ToLower(query)
	queryWords := tokenizeSearch(queryLower)

	type scored struct {
		tool  adapters.ExtractedContent
		score int
	}

	results := make([]scored, 0)
	for _, tool := range deferred {
		toolText := strings.ToLower(tool.ToolName + " " + tool.Content)
		score := 0

		// Exact name match (highest weight)
		toolNameLower := strings.ToLower(tool.ToolName)
		if strings.Contains(queryLower, toolNameLower) {
			score += 100
		}

		// Word overlap
		for _, word := range queryWords {
			if len(word) >= 3 && strings.Contains(toolText, word) {
				score += 10
			}
		}

		if score > 0 {
			results = append(results, scored{tool, score})
		}
	}

	// Sort by score descending
	sort.Slice(results, func(i, j int) bool {
		return results[i].score > results[j].score
	})

	// Return top N
	top := make([]adapters.ExtractedContent, 0, maxResults)
	for i := 0; i < len(results) && i < maxResults; i++ {
		top = append(top, results[i].tool)
	}
	return top
}

// tokenizeSearch splits text into words for search matching.
func tokenizeSearch(text string) []string {
	words := strings.FieldsFunc(text, func(r rune) bool {
		isLowerAlpha := r >= 'a' && r <= 'z'
		isDigit := r >= '0' && r <= '9'
		if isLowerAlpha || isDigit || r == '_' || r == '-' {
			return false
		}
		return true
	})
	return words
}
